version: "3.9"

services:

  backend_test:
    build: .
    container_name: microblog_backend_test
    restart: always
    depends_on:
      - test_db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads

  test_db:
      image: postgres:15
      container_name: test_postgres
      environment:
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_password
        POSTGRES_DB: test_db
      ports:
        - "5433:5432"
      volumes:
        - test_db_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
        interval: 10s
        timeout: 5s
        retries: 5


volumes:
  test_db_data:
